matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      before_script:
        - sudo apt install python-nose
        - sudo apt-get install build-essential libssl-dev libffi-dev python-dev
        - sudo pip2.7 install -U pyopenssl==0.13.1 pyasn1 ndg-httpsclient
        - sudo pip2.7 install -r tests/api_testing/requirements.txt
      script:
        - cd tests/api_testing/
        - bash travis_run_tests.sh
    
    - language: go
      addons:
        firefox: latest
      install:
        - go get -u github.com/jteeuwen/go-bindata/...
        - go get -u -d github.com/Jumpscale/go-raml
        - npm install
      go:
        - 1.7
        - master
      before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        # checkout 6537f1d as temp workaround for https://github.com/Jumpscale/go-raml/issues/306
        - cd $GOPATH/src/github.com/Jumpscale/go-raml && git checkout 6537f1d && ./build.sh && cd -
        - go generate
        - go test -v ./...
        - npm test